### ISSUE TITLE
[Not correct channel,soz] Roku Channel for Bad Voltage

### ISSUE THREAD

**Issue by 3rdwiki** [badvoltage/sailfish-app#12]
Hi there,

I was just looking at a thread on the discussions from JBacon about setting up a Roku Channel for Bad Voltage.
http://community.badvoltage.org/t/bad-voltage-roku-channel/252/2
I was wondering if someone could look into adding this to the main Bad Voltage repository.

Hope this helps the community .

Apologies if this was the wrong channel to post this issue into.

**Comment by flexiondotorg** [comment]
This issue is closed via https://github.com/badvoltage/roku-app/commit/ffc11e6322a50d00b743b1d314d6bada119dc59f
